# Generated by Django 5.2.3 on 2025-06-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
