# Generated by Django 5.1.7 on 2025-07-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
